services:
  - docker

env:
  global:
    # The following secret must be set
    # DOCKER_PASS
    - DOCKER_USER=perrygeo
    - REPO=perrygeo/travis-test   # Dockerhub repository name, not github
    - COMMIT=${TRAVIS_COMMIT::8}
    - DATE=`date +%Y%m%d`
    - TAG="$REPO:$DATE-COMMIT"

before_install:
    - docker build -f Dockerfile -t $TAG .

script:
    - docker run $TAG cat /hi.txt

deploy:
  provider: script
  script: bash docker-push.sh
  on:
      branch: master
