services:
  - docker

env:
  global:
    # The following secret must be set
    # DOCKER_PASS
    - DOCKER_USER=perrygeo
    - REPO=perrygeo/travis-test   # Dockerhub repository name, not github
    - COMMIT=${TRAVIS_COMMIT}

before_install:
    - docker build -f Dockerfile -t $REPO:$COMMIT .

script:
    - docker run -it --rm $REPO:$COMMIT cat /hi.txt

deploy:
  provider: script
  script: bash docker-push.sh
  on:
      branch: master
